using System;
using NUnit.Framework;
using Moq;
using System.Collections.Generic;


class Test1
{
    public Test1(IList<int> list, string str) { }

    public string func1(string a, string b)
    {
        return default(string);
    }
}

[TestFixture]
class Test1Test
{
    private Mock<IList<int>> _list;
    private Test1 _test1;
    [SetUp]
    public void SetUp()
    {
        var str = default(string);
        _list = new Mock<IList<int>>();
        _test1 = new Test1(_list.Object, str);
    }

    [Test]
    public void func1Test()
    {
        var a = default(string);
        var b = default(string);
        var actual = _test1.func1(a, b);
        var expected = default(string);
        Assert.That(actual, Is.EqualTo(expected));
        Assert.Fail("autogenerated");
    }
}